#ifndef CONFIGOPTWIDGET_GLOBAL_H
#define CONFIGOPTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGOPTWIDGET_LIBRARY)
#  define CONFIGOPTWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGOPTWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGOPTWIDGET_GLOBAL_H
