#ifndef SIGNALERMANAGER_GLOBAL_H
#define SIGNALERMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALERMANAGER_LIBRARY)
#  define SIGNALERMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALERMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALERMANAGER_GLOBAL_H
