#ifndef PHASETIMINGTABLEWIDGET_GLOBAL_H
#define PHASETIMINGTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHASETIMINGTABLEWIDGET_LIBRARY)
#  define PHASETIMINGTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHASETIMINGTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHASETIMINGTABLEWIDGET_GLOBAL_H
