#ifndef PHASETABLEWIDGET_GLOBAL_H
#define PHASETABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHASETABLEWIDGET_LIBRARY)
#  define PHASETABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHASETABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHASETABLEWIDGET_GLOBAL_H
