#ifndef SIGNALERONLINESETTINGDLG_GLOBAL_H
#define SIGNALERONLINESETTINGDLG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALERONLINESETTINGDLG_LIBRARY)
#  define SIGNALERONLINESETTINGDLGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALERONLINESETTINGDLGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALERONLINESETTINGDLG_GLOBAL_H
