#ifndef TIMESECTIONTABLEWIDGET_GLOBAL_H
#define TIMESECTIONTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIMESECTIONTABLEWIDGET_LIBRARY)
#  define TIMESECTIONTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIMESECTIONTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMESECTIONTABLEWIDGET_GLOBAL_H
