#ifndef SIGNALERSTATUSWIDGET_GLOBAL_H
#define SIGNALERSTATUSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALERSTATUSWIDGET_LIBRARY)
#  define SIGNALERSTATUSWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALERSTATUSWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALERSTATUSWIDGET_GLOBAL_H
