#ifndef CONFIGMANAGER_GLOBAL_H
#define CONFIGMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGMANAGER_LIBRARY)
#  define CONFIGMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGMANAGER_GLOBAL_H
