#ifndef SCHEDULETABLEWIDGET_GLOBAL_H
#define SCHEDULETABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHEDULETABLEWIDGET_LIBRARY)
#  define SCHEDULETABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCHEDULETABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHEDULETABLEWIDGET_GLOBAL_H
