#ifndef SYSTEMINITER_GLOBAL_H
#define SYSTEMINITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMINITER_LIBRARY)
#  define SYSTEMINITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMINITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMINITER_GLOBAL_H
