#ifndef CHANNELTABLEWIDGET_GLOBAL_H
#define CHANNELTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHANNELTABLEWIDGET_LIBRARY)
#  define CHANNELTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHANNELTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHANNELTABLEWIDGET_GLOBAL_H
