#ifndef TIMINGPLANWIDGET_GLOBAL_H
#define TIMINGPLANWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIMINGPLANWIDGET_LIBRARY)
#  define TIMINGPLANWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIMINGPLANWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMINGPLANWIDGET_GLOBAL_H
