#ifndef TSCABOUTDLG_GLOBAL_H
#define TSCABOUTDLG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TSCABOUTDLG_LIBRARY)
#  define TSCABOUTDLGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TSCABOUTDLGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TSCABOUTDLG_GLOBAL_H
