#ifndef BOTTOMBUTTONSWIDGET_GLOBAL_H
#define BOTTOMBUTTONSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOTTOMBUTTONSWIDGET_LIBRARY)
#  define BOTTOMBUTTONSWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOTTOMBUTTONSWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOTTOMBUTTONSWIDGET_GLOBAL_H
