#ifndef PHASECONFLICTTABLEWIDGET_GLOBAL_H
#define PHASECONFLICTTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHASECONFLICTTABLEWIDGET_LIBRARY)
#  define PHASECONFLICTTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHASECONFLICTTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHASECONFLICTTABLEWIDGET_GLOBAL_H
