#ifndef UNITPARAMTABLEWIDGET_GLOBAL_H
#define UNITPARAMTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNITPARAMTABLEWIDGET_LIBRARY)
#  define UNITPARAMTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNITPARAMTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNITPARAMTABLEWIDGET_GLOBAL_H
