#ifndef FILEREADERWRITER_GLOBAL_H
#define FILEREADERWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEREADERWRITER_LIBRARY)
#  define FILEREADERWRITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEREADERWRITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEREADERWRITER_GLOBAL_H
