#ifndef COMMANDCALLBACK_GLOBAL_H
#define COMMANDCALLBACK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMANDCALLBACK_LIBRARY)
#  define COMMANDCALLBACKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMANDCALLBACKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMANDCALLBACK_GLOBAL_H
