#ifndef DETECTORTABLEWIDGET_GLOBAL_H
#define DETECTORTABLEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DETECTORTABLEWIDGET_LIBRARY)
#  define DETECTORTABLEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DETECTORTABLEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DETECTORTABLEWIDGET_GLOBAL_H
